apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachineTemplate
metadata:
  name: ${CLUSTER_NAME}-control-plane
  namespace: default
spec:
  template:
    spec:
      networkInterfaces:
      - subnetName: control-plane-subnet
        privateIPConfigs: 110 # matching the max pods per node.
